# SPDX-License-Identifier copyleft-next-0.3.1
---

infer_uid_and_group: True

data_path: "/data"
data_user: "vagrant"
data_group: "vagrant"

data_device: "/dev/nvme0n1"
data_fstype: "xfs"
data_label: "data"
data_fs_opts: "-L {{ disk_setup_label }}"

# Linux target defaults
target_linux_admin_name: "Hacker Amanda"
target_linux_admin_email: "devnull@kernel.org"
target_linux_git: "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
target_linux_shallow_depth: 0
target_linux_tree: "linux-stable"
target_linux_dir_path: "{{ data_path }}/{{ target_linux_tree }}"

target_linux_tag: "v4.19.133"
target_linux_delta_file:
target_linux_config: "config-{{ target_linux_tag }}"
make: "make"
# Once ansible v2.10 becomes available we can move on to using
# ansible_processor_nproc but that was merged in 2020:
# The commit is 34db57a47f875d11c4068567b9ec7ace174ec4cf
# introduce fact "ansible_processor_nproc": number of usable vcpus #66569
# https://github.com/ansible/ansible/pull/66569
target_linux_make_cmd: "{{ make }} -j{{ ansible_processor_vcpus }}"
target_linux_make_install_cmd: "{{ make }} modules_install install"

# If defined we'll apply this delta for you.
# target_linux_extra_patch: foo.patch

bootlinux_9p: False
bootlinux_9p_host_path: "/dev/null"
bootlinux_9p_msize: 0
bootlinux_9p_fsdev: "ignore"
bootlinux_9p_mount_tag: "ignore"
bootlinux_9p_security_model: "none"
bootlinux_9p_driver: "virtio-9p-pci"
