- name: Run update-grub
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "update-grub"
  register: grub_update
  changed_when: "grub_update.rc == 0"
  tags: [ 'linux', 'manual-update-grub', 'console' ]
