- name: Disable Grub menu auto-hide
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: grub2-editenv - unset menu_auto_hide

- name: Determine if system was booted using UEFI
  stat:
    path: /sys/firmware/efi/efivars
  register: efi_boot

- name: Use /etc/grub2.cfg as the grub configuration file
  set_fact:
    grub_config_file: '/etc/grub2.cfg'
  when:
    not efi_boot.stat.exists

- name: Use /etc/grub2-efi.cfg as the configuration file
  set_fact:
    grub_config_file: '/etc/grub2-efi.cfg'
  when:
    efi_boot.stat.exists

- name: Run update-grub
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "grub2-mkconfig -o {{ grub_config_file }}"
  register: grub_update
  changed_when: "grub_update.rc == 0"
  tags: [ 'linux', 'manual-update-grub', 'console' ]
