---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install vagrant and other dependencies
  include_tasks: install-deps/main.yml

- name: Create a base storage pool if it does not exist
  become: yes
  become_method: sudo
  file:
    path: "{{ storage_pool_path }}"
    state: directory
    mode: 'g+rw,o+rx'
    owner: "{{ storage_pool_user }}"
    group: "{{ storage_pool_group }}"
  delegate_to: localhost
  run_once: true
  when:
    - libvirt_storage_pool_create|bool

- name: Create a kdevops specific storage pool for vagrant if it does not exist
  become: yes
  become_method: sudo
  file:
    path: "{{ kdevops_storage_pool_path }}"
    state: directory
    mode: 'o+rwxs,g+rxws'
    owner: "{{ kdevops_storage_pool_user }}"
    group: "{{ kdevops_storage_pool_group }}"
  delegate_to: localhost
  run_once: true
  when:
    - libvirt_storage_pool_create|bool
