---
# Install dependencies on Debian
- name: Set up apt for Debian testing
  become: yes
  become_method: sudo
  template:
    src: debian/sources.list.testing
    dest: /etc/apt/sources.list
  tags: [ 'apt', 'config' ]

- name: Allow for distro source change / upgrade
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "apt-get update  --allow-releaseinfo-change"
  register: release_info_changed
  changed_when: "release_info_changed.rc == 0"
  args:
    warn: no
  tags: [ 'apt', 'release-info-change' ]
  when:
    - devconfig_try_upgrade|bool

- name: Update apt cache and do dist-upgrade
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    upgrade: full
  tags: [ 'apt', 'cache' ]
  when:
    - devconfig_try_upgrade|bool

- name: Install our generic dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - nvme-cli
      - ssh
      - bison
      - flex
      - libelf-dev
      - libncurses-dev
      - screen
      - git
      - e2fsprogs
      - xfsprogs
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-dev
    state: present
    update_cache: yes
  tags: [ 'kdevops', 'deps' ]
  when:
    - devconfig_try_install_kdevtools|bool
