# SPDX-License-Identifier copyleft-next-0.3.1
---

# Your target home directory
data_home_dir: "/home/vagrant"

# On your own system
dev_gitconfig_src: "~/.gitconfig"
# Where we copy it to
dev_gitconfig_dest: "{{ data_home_dir }}/.gitconfig"

# The bash script we check for on the virtual machine
dev_bash_config:  "{{ data_home_dir }}/.bashrc"
dev_bash_config_root:  "/root/.bashrc"

dev_bash_config_hacks_name: "enhance-bash"
dev_bash_config_hacks_src: "~/.{{ dev_bash_config_hacks_name }}"
dev_bash_config_hacks_generic: "~/.{{ dev_bash_config_hacks_name }}"
dev_bash_config_hacks_dest: "{{ data_home_dir }}/.{{ dev_bash_config_hacks_name }}"
dev_bash_config_hacks_root: "/root/.{{ dev_bash_config_hacks_name }}"

devconfig_try_refresh_repos: False
devconfig_try_upgrade: False
devconfig_try_install_kdevtools: False

devconfig_repos_addon: False
devconfig_repos_addon_list:

suse_register_system: False
suse_registration_code: 0

devconfig_enable_console: False
devconfig_enable_kotd: False
devconfig_has_kotd_repo: False
devconfig_kotd_repo: "http://ignore.com"
devconfig_kotd_repo_name: "ignore"
devconfig_enable_systemd_watchdog: False

devconfig_enable_sysctl_tuning: False
devconfig_enable_sysctl_mm_overcommit_memory: False
devconfig_sysctl_conf: "/etc/sysctl.conf"
devconfig_sysctl_mm_overcommit_memory: 0

rhel_org_id: ""
rhel_activation_key: ""

kdevops_cli_install: False
devconfig_enable_systemd_journal_remote: False
devconfig_systemd_journal_remote_url: "http://192.168.124.1"
devconfig_systemd_journal_remote_path: "/var/log/journal/remote/"

devconfig_enable_systemd_timesyncd: False
devconfig_enable_systemd_timesyncd_copy_host_timezone: False
devconfig_enable_systemd_timesyncd_ntp: False
devconfig_enable_systemd_timesyncd_ntp_google: False
devconfig_enable_systemd_timesyncd_ntp_debian: False
devconfig_enable_systemd_timesyncd_ntp_google_debian: False
devconfig_enable_systemd_timesyncd_timezone: False
devconfig_systemd_timesyncd_timezone: "UTC"
