---
- name: Set generic SUSE specific distro facts
  set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Set SLE specific version labels to make checks easier
  set_fact:
    is_sle10: '{{ ansible_distribution_major_version == "10" }}'
    is_sle11: '{{ ansible_distribution_major_version == "11" }}'
    is_sle12: '{{ ansible_distribution_major_version == "12" }}'
    is_sle15: '{{ ansible_distribution_major_version == "15" }}'
    is_sle10sp3: '{{ ansible_distribution_version == "10.3" }}'
    is_sle11sp1: '{{ ansible_distribution_version == "11.1" }}'
    is_sle11sp4: '{{ ansible_distribution_version == "11.4" }}'
    is_sle12sp1: '{{ ansible_distribution_version == "12.1" }}'
    is_sle12sp3: '{{ ansible_distribution_version == "12.3" }}'
    is_sle15sp2: '{{ ansible_distribution_version == "15.2" }}'
    is_sle15sp3: '{{ ansible_distribution_version == "15.3" }}'
  when:
    - is_sle|bool

- name: By default we assume we have figured out how to add repos on a release
  set_fact:
    repos_present: true

- name: Lets us disable things which require a zypper repo present
  set_fact:
    repos_present: false
  when:
    - is_sle|bool
    - is_sle10|bool or is_sle11|bool

- name: Install local dependencies for fstests command and control
  become: yes
  become_method: sudo
  zypper:
    name:
      - python3-junit-xml
      - python3-pip
    state: present
  when:
    - repos_present|bool
    - install_local_deps|bool
  tags: [ 'local_deps' ]

- name: Install junitparser
  become: yes
  become_method: sudo
  pip:
    name:
      - junitparser
  when:
    - install_local_deps|bool
  tags: [ 'local_deps' ]
