# SPDX-License-Identifier copyleft-next-0.3.1
---
# Our sensible defaults for the blktests role.
#
# We default to not run tests.
kdevops_run_blktests: False
run_tests_on_failures: False
blktests_skip_run: False

# Ror instance you can use "-g quick" but note that this may produce
# not results as all quick tests may be expunded.
oscheck_extra_args: ""
limit_tests: ""

blktests_git: "https://github.com/osandov/blktests.git"
blktets_data: "{{ data_path }}/blktests"
blktests_data_target: "/usr/local/blktests/"
blktests_test_devs: "/dev/null"

nbd_git: "https://github.com/NetworkBlockDevice/nbd.git"
nbd_version: "nbd-3.21"
nbd_data: "{{data_path}}/nbd"

compile_dbench: False
