# SPDX-License-Identifier copyleft-next-0.3.1
---
# Our sensible defaults for the common shared workflows role.
workflow_install_postfix: false
workflow_install_watchdog: false

postfix_relayhost: "smtp.gmail.com"
postfix_relayport: "587"
postfix_mailhub: "{{ postfix_mailhub_server }}:{{ postfix_mailhub_port }}"
postfix_hostname: "{{ ansible_hostname }}"
postfix_domain: "{{ ansible_domain }}"
postfix_auth_user: 'foo@gmail.com'
postfix_auth_pass: 'mysuperd00perPassword'
postfix_setgid_group: "postdrop"
postfix_daemon_directory: "/usr/lib/postfix/bin"

suports_watchdog: True

# defaults file for the watchdog - whiskerlabs.watchdog
#
# Name of the watchdog service according to the target hosts' init system.
watchdog_service_name: watchdog.service

# See watchdog.conf manpage [1] for details on watchdog configuration options.
#
# [1] http://linux.die.net/man/5/watchdog.conf

# Path to the watchdog device.
watchdog_device: /dev/watchdog

# Email address to to which to send admin mail.
watchdog_admin: "devnull@kernel.org"

# Interval between writes to the watchdog device, in seconds.
watchdog_interval: "10"

# Number of intervals skipped before logging messages (see
# watchdog.conf manpage).
watchdog_logtick: ""

# Directory in which to capture the stdout and stderr from
# repair-binary and test-binary execution.
watchdog_log_dir: ""

# Whether or not to lock the watchdog in memory so that it is never
# swapped out.
watchdog_realtime: yes

# Scheduler priority for realtime mode.
watchdog_priority: 1

# A list of IP addresses to be used with ping mode.
# e.g. [192.168.0.1]
watchdog_ping_addrs: []

# A list of network interfaces naems to be used with network mode.
# e.g. [eth0]
watchdog_interfaces: []

# A list of file items to be used with file mode. Items must contain a
# `name` field and optionally a `change` field (see watchdog.conf
# manpage).
# e.g. - { name: "/var/run/thing.pid", change: 60 }
watchdog_files: []

# A list of pidfiles to be used with server test mode.
# e.g. [/var/run/syslogd.pid]
watchdog_pidfiles: []

# Maximum allowed load averages, over one-, five-, and 15-minute
# spans.
watchdog_max_load_1: ""
watchdog_max_load_5: ""
watchdog_max_load_15: ""

# Minimum amount of virtual memory, in number of pages.
watchdog_min_memory: ""

# Binary used to execute user-defined repair actions.
watchdog_repair_binary: ""

# Maximum duration over which user-defined repair actions are allowed
# to run.
watchdog_repair_timeout: ""

# Binary used to execute user-defined tests.
watchdog_test_binary: ""

# Maximum duration over which user-defined tests are allowed to run.
watchdog_test_timeout: ""

# Path to the temperature device.
watchdog_temperature_device: ""

# Maximum allowed device temperature.
watchdog_max_temperature: ""
