---
- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: install

- name: Install libvirt / kvm dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - libvirt-daemon
      - libvirt-daemon-system
      - libvirt-clients
      - qemu-kvm
      - qemu-system-x86
      - qemu-utils
    state: present
  tags: install

- name: Enable libvirtd
  become: yes
  become_method: sudo
  systemd:
    name: libvirtd
    enabled: yes
    masked: no

- name: Make sure libvirtd is running
  become: yes
  become_method: sudo
  systemd:
    state: started
    name: libvirtd
