---
- name: Ensure required /media/ directories are created
  become: yes
  become_method: sudo
  file:
    state: directory
    path: "/media/{{ item }}"
  with_items:
    - scratch
    - "{{ sparsefiles_path }}"
    - test

# tasks to install dependencies for oscheck
- name: oscheck distribution ospecific setup
  import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- import_tasks: tasks/install-deps/suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- import_tasks: tasks/install-deps/redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
