---
- name: Set generic SUSE specific distro facts
  set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'
  tags: [ 'vars' ]

- name: Install kdevops generic dependencies
  become: yes
  become_method: sudo
  zypper:
    name:
      - gcc
      - make
      - bison
      - flex
      - m4
      - bc
      - sed
      - ncurses-devel
  when:
    - is_tumbleweed
