---
- name: Create a new LVM partition
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  community.general.lvol:
    vg: exports
    lv: "{{ export_volname }}"
    size: "{{ export_size }}"
  when:
    - export_fstype != "tmpfs"

- name: Format new volume for {{ export_fstype }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  filesystem:
    fstype: "{{ export_fstype }}"
    dev: "/dev/exports/{{ export_volname }}"
  when:
    - export_fstype != "tmpfs"

- name: Mount volume under {{ nfsd_export_path }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  throttle: 1  # running this in parallel can clobber fstab changes
  mount:
    path: "{{ nfsd_export_path }}/{{ export_volname }}"
    src: "/dev/exports/{{ export_volname }}"
    fstype: "{{ export_fstype }}"
    state: mounted
  when:
    - export_fstype != "tmpfs"

- name: Mount tmpfs under {{ nfsd_export_path }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  throttle: 1  # running this in parallel can clobber fstab changes
  mount:
    path: "{{ nfsd_export_path }}/{{ export_volname }}"
    src: "tmpfs"
    fstype: "tmpfs"
    state: mounted
  when:
    - export_fstype == "tmpfs"

- name: Ensure {{ export_volname }} has correct permissions
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  file:
    state: directory
    path: "{{ nfsd_export_path }}/{{ export_volname }}"
    owner: "{{ export_user }}"
    group: "{{ export_group }}"

- name: Test whether SELinux is enabled
  command: /usr/sbin/selinuxenabled
  register: selinux_status
  delegate_to: "{{ server_host }}"
  changed_when: False
  failed_when: False

- name: Fix SELinux file context under new mount
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  command: /usr/sbin/restorecon -R "{{ nfsd_export_path }}/{{ export_volname }}"
  when: selinux_status.rc == 0

- name: Ensure /etc/exports.d exists
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  file:
    state: directory
    path: "/etc/exports.d"
    owner: "root"
    group: "root"
    mode: '644'

- name: Copy export options to a template variable
  set_fact:
    template_export_options: "{{ export_options }}"

- name: Check for an fsid= export option
  set_fact:
    fsid_is_present: '{{ "fsid=" in export_options }}'
  when:
    - export_fstype == "tmpfs"

- name: Generate a unique fsid
  command: "uuidgen -r"
  register: export_fsid
  when:
    - export_fstype == "tmpfs"
    - not fsid_is_present|bool

- name: Add an fsid= export option
  set_fact:
    template_export_options: "{{ export_options }},fsid={{ export_fsid.stdout }}"
  when:
    - export_fstype == "tmpfs"
    - not fsid_is_present|bool

- name: Create an exports.d file for the new fs
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  template:
    src: exports.j2
    dest: /etc/exports.d/{{ export_volname }}.exports
    owner: root
    group: root
    mode: 0644

- name: Reload the exports table
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  delegate_to: "{{ server_host }}"
  command: /usr/sbin/exportfs -ra
