- name: Add custom repositories
  become: yes
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ kdevops_devconfig_custom_repos | trim | split(',') }}"
  when: kdevops_devconfig_custom_repos | trim | length > 1

- name: Install custom packages
  become: yes
  become_method: sudo
  yum:
    name: "{{ item }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  with_items: "{{ kdevops_devconfig_custom_packages | trim | split(',') }}"
  when: kdevops_devconfig_custom_packages | trim | length > 1
