---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars
  when:
    - postfix_relay_host_setup|bool

- name: check to see if /etc/postfix/main.cf exists
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  stat:
    path=/etc/postfix/main.cf
  register: postfix_config_main_file
  when:
    - postfix_relay_host_setup|bool
  tags: [ 'postfix' ]

- name: Set relayhost on /etc/postfix/main.cf
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^(relayhost)(.*)'
    line: 'relayhost = {{ postfix_relay_host }}'
  when:
    - postfix_config_main_file.stat.exists
    - postfix_relay_host_setup|bool
  tags: [ 'postfix' ]

- name: Enable and restart postfix service
  become: yes
  become_method: sudo
  systemd:
    name: postfix
    enabled: yes
    state: restarted
    masked: no
  when:
    - postfix_config_main_file.stat.exists
    - postfix_relay_host_setup|bool
  tags: postfix
