---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- include_role:
    name: create_data_partition
  tags: [ 'data_partition' ]

- name: Install build-deps for btrfs_progs as per each Linux distribution
  include_tasks: install-deps/main.yml
  when:
    - btrfs_progs_build|bool

- name: Assume we won't build btrfs_progs first
  set_fact:
    build_btrfs_progs_now: False
  tags: vars

- name: Annotate when we are building btrfs_progs
  set_fact:
    build_btrfs_progs_now: True
  when:
    - btrfs_progs_build|bool
  tags: vars

- name: Set bindir for debian systems
  set_fact:
    bindir: "/usr/bin"
  when: ansible_facts['os_family']|lower == 'debian'
  tags: vars

- name: Set bindir for non-debian systems
  set_fact:
    bindir: "/usr/sbin"
  when: ansible_facts['os_family']|lower != 'debian'
  tags: vars

- name: git clone btrfs_progs
  environment:
    GIT_SSL_NO_VERIFY:  true
  git:
    repo: "{{ btrfs_progs_git }}"
    dest: "{{ btrfs_progs_data }}"
    version: "{{ btrfs_progs_version }}"
  when:
    - build_btrfs_progs_now|bool

- name: run make clean-all for btrfs_progs
  make:
    chdir: "{{ btrfs_progs_data }}"
    target: clean-all
  ignore_errors: yes

- name: run autogen.sh for btrfs_progs
  command: "./autogen.sh"
  tags: [ 'btrfs_progs', 'configure' ]
  args:
    chdir: "{{ btrfs_progs_data }}"
  when:
    - build_btrfs_progs_now|bool

- name: run configure for btrfs_progs
  command: "./configure --disable-documentation --enable-experimental --bindir={{ bindir }} --prefix=/usr --exec-prefix=/usr --disable-python"
  tags: [ 'btrfs_progs', 'configure' ]
  args:
    chdir: "{{ btrfs_progs_data }}"
  when:
    - build_btrfs_progs_now|bool

- name: Get nproc
  command: "{{ num_jobs }}"
  tags: [ 'btrfs_progs', 'configure' ]
  register: nproc
  when:
    - build_btrfs_progs_now|bool

- name: Build btrfs_progs
  make:
    chdir: "{{ btrfs_progs_data }}"
    jobs: "{{ nproc.stdout }}"
  tags: [ 'btrfs_progs', 'build' ]
  when:
    - build_btrfs_progs_now|bool

- name: Install btrfs_progs
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{ make }} install"
  args:
    chdir: "{{ btrfs_progs_data }}"
  tags: [ 'btrfs_progs', 'install' ]
  when:
    - build_btrfs_progs_now|bool
