- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Set the path where we collect our local pynfs results
  set_fact:
    pynfs_local_results_dir: "../workflows/pynfs/results"
  tags: [ 'vars' ]

- name: Clean up our localhost results directory and files
  local_action: file path="{{ pynfs_local_results_dir }}/" state=absent
  run_once: true
  tags: [ 'clean_local_results', 'first_run' ]

- name: Create the local results directory
  local_action: file path="{{ pynfs_local_results_dir }}/" state=directory
  run_once: true
  tags: [ 'first_run' ]

- include_role:
    name: create_data_partition
  tags: [ 'data_partition' ]

# Distro specific
- include: tasks/install-deps/main.yml

- name: Remove old pynfs dir as we always clone a fresh tree
  tags: [ 'git', 'pynfs' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    path: "{{ pynfs_data }}"
    state: absent

- name: git clone pynfs
  tags: [ 'git', 'pynfs' ]
  git:
    repo: "{{ pynfs_git }}"
    dest: "{{ pynfs_data }}"
    update: yes
    version: master
  retries: 3
  delay: 5
  register: result
  until: not result.failed

- name: Build pynfs
  tags: [ 'pynfs' ]
  command: ./setup.py build
  args:
    chdir: "{{ pynfs_data }}"

- name: Wait until nfsd grace period ends
  tags: [ 'run_tests' ]
  command: /usr/bin/grep Y /proc/fs/nfsd/v4_end_grace
  register: result
  retries: 90
  delay: 1
  until: result.rc == 0

- name: Run pynfs
  tags: [ 'run_tests' ]
  shell: "./testserver.py --json={{ pynfs_data }}/pynfs-{{ item }}-results.json --maketree --uid=0 --gid=0 localhost:{{ nfsd_export_path }} all || true"
  args:
    chdir: "{{ pynfs_data }}/nfs{{ item }}"
  with_items:
    - 4.0
    - 4.1

- name: Get used target kernel version
  tags: [ 'copy_results' ]
  command: "uname -r"
  register: uname_cmd

- name: Store kernel_rev variable
  tags: [ 'copy_results' ]
  set_fact:
    kernel_rev: "{{ uname_cmd.stdout_lines | regex_replace('\\]') | regex_replace('\\[') | replace(\"'\",'') }}"
  run_once: true

- name: Copy the latest results over when we're done
  tags: [ 'copy_results' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  fetch:
    src: "{{ pynfs_data }}/pynfs-{{ item }}-results.json"
    dest: "{{ pynfs_local_results_dir }}/{{ kernel_rev }}-v{{ item }}.json"
    flat: yes
  with_items:
    - 4.0
    - 4.1
