# SPDX-License-Identifier copyleft-next-0.3.1                                   
---                                                                             
postfix_relay_host_setup: False
postfix_relay_host: "some.example.com
