---
# tasks to install dependencies for dbench
- name: dbench distribution ospecific setup
  import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'

# Other distros can be added on a need basis here
