---
- name: Dump pci output in machine-readible form
  shell: "lspci -Dvmmm > {{ topdir_path }}/.dynamic-kconfig.pci.txt"
  when:
    - kdevops_pcie_dynamic_kconfig

- name: Generate libvirt PCI-E kcofig files
  shell: "./python/workflows/dynamic-kconfig/gen-dynamic-pci.py {{ topdir_path }}/.dynamic-kconfig.pci.txt > {{ topdir_path }}/vagrant/Kconfig.passthrough_libvirt.generated"
  when:
    - kdevops_pcie_dynamic_kconfig
