---
- name: Set generic SUSE specific distro facts
  set_fact:
    is_sle: '{{ (ansible_distribution == "SLES") or (ansible_distribution == "SLED") }}'
    is_leap: '{{ "Leap" in ansible_distribution }}'
    is_tumbleweed: '{{ "openSUSE Tumbleweed" == ansible_distribution }}'

- name: Install QEMU build dependencies
  become: yes
  become_method: sudo
  zypper:
    name:
      - acpica
      - alsa-devel
      - atk-devel
      - at-spi2-atk-devel
      - at-spi2-core
      - at-spi2-core-devel
      - binutils-devel
      - brlapi-devel
      - cairo-devel
      - cmake
      - cmake-full
      - cross-ppc64-binutils
      - cross-ppc64-gcc12
      - cross-riscv64-binutils
      - cross-riscv64-gcc12
      - cross-riscv64-glibc-devel
      - cross-riscv64-linux-glibc-devel
      - cups-config
      - cyrus-sasl-bdb-devel
      - dbus-1-devel
      - desktop-file-utils
      - dos2unix
      - fdupes
      - fontconfig
      - fontconfig-devel
      - freetype2-devel
      - fribidi-devel
      - gcc12-c++
      - gcc-c++
      - gdk-pixbuf-devel
      - gdk-pixbuf-loader-rsvg
      - gdk-pixbuf-query-loaders
      - gettext-its-gtk4
      - gettext-tools
      - gio-branding-openSUSE
      - girepository-1_0
      - glib2-devel
      - glib2-tools
      - glibc-32bit
      - glibc-devel-32bit
      - glusterfs
      - glusterfs-devel
      - gmp-devel
      - gnutls
      - graphite2-devel
      - gstreamer
      - gstreamer-plugins-base
      - gtk3-data
      - gtk3-devel
      - gtk3-schema
      - gtk3-tools
      - harfbuzz-devel
      - hicolor-icon-theme
      - infiniband-diags
      - libacl-devel
      - libarchive13
      - libasound2
      - libatk-1_0-0
      - libatk-bridge-2_0-0
      - libatspi0
      - libattr-devel
      - libavahi-client3
      - libavahi-common3
      - libblkid-devel
      - libbrlapi0_8
      - libbrotli-devel
      - libbrotlienc1
      - libbz2-devel
      - libcacard0
      - libcacard-devel
      - libcairo2
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcap-ng-devel
      - libcdda_interface0
      - libcdda_paranoia0
      - libcelt0-2
      - libcolord2
      - libcrypto49
      - libcups2
      - libcurl-devel
      - libdatrie1
      - libdatrie-devel
      - libdrm2
      - libdrm_amdgpu1
      - libdrm-devel
      - libdrm_intel1
      - libdrm_nouveau2
      - libdrm_radeon1
      - libepoxy0
      - libepoxy-devel
      - libevent-2_1-7
      - libexpat-devel
      - libfdt1
      - libfdt-devel
      - libffi-devel
      - libFLAC8
      - libfontconfig1
      - libfreebl3
      - libfribidi0
      - libgbm1
      - libgbm-devel
      - libgcrypt-devel
      - libgdk_pixbuf-2_0-0
      - libgfchangelog0
      - libgio-2_0-0
      - libgirepository-1_0-1
      - libglusterd0
      - libglvnd
      - libglvnd-devel
      - libgmodule-2_0-0
      - libgmpxx4
      - libgnutls30
      - libgnutls-dane0
      - libgnutls-devel
      - libgobject-2_0-0
      - libgpg-error-devel
      - libgraphene-1_0-0
      - libgraphite2-3
      - libgstallocators-1_0-0
      - libgstapp-1_0-0
      - libgstaudio-1_0-0
      - libgstgl-1_0-0
      - libgstpbutils-1_0-0
      - libgstreamer-1_0-0
      - libgstriff-1_0-0
      - libgsttag-1_0-0
      - libgstvideo-1_0-0
      - libgthread-2_0-0
      - libgtk-3-0
      - libgudev-1_0-0
      - libharfbuzz0
      - libharfbuzz-gobject0
      - libharfbuzz-icu0
      - libharfbuzz-subset0
      - libhogweed6
      - libibmad5
      - libibnetdisc5
      - libibumad3
      - libicu71
      - libicu71-ledata
      - libicu-devel
      - libidn2-devel
      - libiscsi9
      - libiscsi-devel
      - libjack0
      - libjack-devel
      - libjacknet0
      - libjackserver0
      - libjbig2
      - libjpeg62
      - libjpeg62-devel
      - libjpeg8
      - libjsoncpp25
      - liblcms2-2
      - libLLVM14
      - libmount-devel
      - libmpath0
      - libndctl-devel
      - libnettle8
      - libnettle-devel
      - libnfs14
      - libnfs-devel
      - libnuma-devel
      - libogg0
      - libopus0
      - liborc-0_4-0
      - libOSMesa8
      - libOSMesa-devel
      - libpango-1_0-0
      - libpcap1
      - libpciaccess0
      - libpciaccess-devel
      - libpcre16-0
      - libpcre2-16-0
      - libpcre2-32-0
      - libpcre2-posix3
      - libpcrecpp0
      - libpcreposix0
      - libpixman-1-0
      - libpixman-1-0-devel
      - libpmem-devel
      - libpng16-compat-devel
      - libpng16-devel
      - libprotobuf-c1
      - libpulse0
      - libpulse-devel
      - libpulse-mainloop-glib0
      - librados-devel
      - libradospp-devel
      - librbd-devel
      - libressl-devel
      - librhash0
      - librsvg-2-2
      - libsamplerate0
      - libseccomp-devel
      - libselinux-devel
      - libsepol-devel
      - libslirp0
      - libslirp-devel
      - libsndfile1
      - libsodium23
      - libsoftokn3
      - libspeex1
      - libspice-server1
      - libspice-server-devel
      - libssh-devel
      - libssl52
      - libstdc++6-devel-gcc12
      - libstdc++-devel
      - libtasn1-devel
      - libthai0
      - libthai-data
      - libthai-devel
      - libtheoradec1
      - libtheoraenc1
      - libtiff5
      - libtiff-devel
      - libtls25
      - libunbound8
      - libunwind8
      - liburing2
      - liburing-devel
      - libusb-1_0-devel
      - libusbredirhost1
      - libusbredirparser1
      - libuuid-devel
      - libuv1
      - libvdehist0
      - libvdemgmt0
      - libvdeplug3
      - libvdeplug-devel
      - libvirglrenderer1
      - libvisual-0_4-0
      - libvorbis0
      - libvorbisenc2
      - libvte-2_91-0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libX11-6
      - libX11-data
      - libX11-devel
      - libX11-xcb1
      - libXau6
      - libXau-devel
      - libxcb1
      - libxcb-composite0
      - libxcb-damage0
      - libxcb-devel
      - libxcb-dpms0
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libxcb-randr0
      - libxcb-record0
      - libxcb-render0
      - libxcb-res0
      - libxcb-screensaver0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xf86dri0
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xinput0
      - libxcb-xkb1
      - libxcb-xtest0
      - libxcb-xv0
      - libxcb-xvmc0
      - libXcomposite1
      - libXcomposite-devel
      - libXcursor1
      - libXcursor-devel
      - libXdamage1
      - libXdamage-devel
      - libXext6
      - libXext-devel
      - libXfixes3
      - libXfixes-devel
      - libXft2
      - libXft-devel
      - libXi6
      - libXi-devel
      - libXinerama1
      - libXinerama-devel
      - libxkbcommon0
      - libxkbcommon-devel
      - libXrandr2
      - libXrandr-devel
      - libXrender1
      - libXrender-devel
      - libxshmfence1
      - libXtst6
      - libXtst-devel
      - libXv1
      - libXxf86vm1
      - libzstd-devel
      - lzfse
      - lzfse-devel
      - lzo-devel
      - Mesa
      - Mesa-devel
      - Mesa-dri
      - Mesa-dri-devel
      - Mesa-gallium
      - Mesa-KHR-devel
      - Mesa-libEGL1
      - Mesa-libEGL-devel
      - Mesa-libGL1
      - Mesa-libglapi0
      - Mesa-libglapi-devel
      - Mesa-libGL-devel
      - Mesa-libGLESv1_CM-devel
      - Mesa-libGLESv2-devel
      - meson
      - mozilla-nspr
      - mozilla-nspr-devel
      - mozilla-nss
      - mozilla-nss-certs
      - mozilla-nss-devel
      - multipath-tools-devel
      - ninja
      - p11-kit-devel
      - pango-devel
      - pcre2-devel
      - pcre-devel
      - python38-alabaster
      - python38-apipkg
      - python38-appdirs
      - python38-Babel
      - python38-cached-property
      - python38-certifi
      - python38-cffi
      - python38-charset-normalizer
      - python38-cryptography
      - python38-docutils
      - python38-dragonmapper
      - python38-hanzidentifier
      - python38-idna
      - python38-imagesize
      - python38-importlib-metadata
      - python38-iniconfig
      - python38-Jinja2
      - python38-loguru
      - python38-MarkupSafe
      - python38-more-itertools
      - python38-ordered-set
      - python38-packaging
      - python38-prettytable
      - python38-py
      - python38-pycparser
      - python38-Pygments
      - python38-pyOpenSSL
      - python38-pyparsing
      - python38-pytz
      - python38-requests
      - python38-setuptools
      - python38-six
      - python38-snowballstemmer
      - python38-Sphinx
      - python38-sphinxcontrib-applehelp
      - python38-sphinxcontrib-devhelp
      - python38-sphinxcontrib-htmlhelp
      - python38-sphinxcontrib-jsmath
      - python38-sphinxcontrib-qthelp
      - python38-sphinxcontrib-serializinghtml
      - python38-sphinxcontrib-websupport
      - python38-sphinx_rtd_theme
      - python38-urllib3
      - python38-wcwidth
      - python38-zhon
      - python38-zipp
      - rdma-core-devel
      - rsocket
      - shared-mime-info
      - snappy-devel
      - spice-protocol-devel
      - systemd-devel
      - system-user-brltty
      - system-user-lp
      - system-user-pulse
      - typelib-1_0-Atk-1_0
      - typelib-1_0-Atspi-2_0
      - typelib-1_0-GdkPixbuf-2_0
      - typelib-1_0-GdkPixdata-2_0
      - typelib-1_0-Gtk-3_0
      - typelib-1_0-HarfBuzz-0_0
      - typelib-1_0-Pango-1_0
      - typelib-1_0-Vte-2.91
      - unbound-anchor
      - update-desktop-files
      - usbredir-devel
      - vde2
      - virglrenderer-devel
      - vte-devel
      - wayland-devel
      - xen-devel
      - xfsprogs-devel
      - xkeyboard-config
      - xorgproto-devel
      - xz-devel
      - zlib-devel
  when:
    - is_tumbleweed
