---
- name: Enable the CodeReady repo
  become: yes
  command: /usr/bin/dnf config-manager --enable codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms
  when:
    - rhel_org_id is defined
    - rhel_activation_key is defined

- name: Install build dependencies for pynfs
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  vars:
    packages:
      - gcc
      - git-core
      - make
      - krb5-devel
      - python3-devel
      - swig
      - python3-gssapi
      - python3-ply
