# SPDX-License-Identifier copyleft-next-0.3.1
---
disk_setup_device: "/dev/some-block-device"
disk_setup_fstype: "xfs"
# For instance use nofail if you want your bootup to work
# even if mount did not succeed.
disk_setup_mount_opts: "defaults"
disk_setup_label: "data"
disk_setup_fs_opts: "-L {{ disk_setup_label }}"
disk_setup_path: "/data"
disk_setup_user: "root"
disk_setup_group: "root"
disk_setup_mode: "u=rwx,g=rwx,o=rwxt"
