---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install systemd-timesyncd
  include_tasks: install-deps/main.yml

- name: Set up the server /etc/systemd/timesyncd.conf
  tags: [ 'timesyncd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: "timesyncd.conf.j2"
    dest: "/etc/systemd/timesyncd.conf"
    force: yes
    trim_blocks: True
    lstrip_blocks: True
  when:
    - devconfig_enable_systemd_timesyncd|bool

- name: Set timezone on the host to {{ devconfig_systemd_timesyncd_timezone }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "timedatectl set-timezone {{ devconfig_systemd_timesyncd_timezone }}"
  when:
    - devconfig_enable_systemd_timesyncd_timezone|bool

- name: Enable NTP
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "timedatectl set-ntp true"
  when:
    - devconfig_enable_systemd_timesyncd_ntp|bool

- name: Restart systemd-timesyncd.service on the server
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.systemd_service:
    name: systemd-timesyncd.service
    daemon_reload: true
    enabled: true
    state: restarted
  when:
    - devconfig_enable_systemd_timesyncd|bool

- name: Ensure systemd-timesyncd.service is running on the server
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "timedatectl status"
  when:
    - devconfig_enable_systemd_timesyncd|bool
