---
- name: oscheck distribution ospecific setup
  import_tasks: debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- import_tasks: suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- import_tasks: redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'
