---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install dependencies
  include_tasks: install-deps/main.yml

- name: git clone dbench
  git:
    repo: "{{ dbench_git }}"
    dest: "{{ dbench_data }}"
    update: yes
  tags: [ 'git', 'dbench' ]
  when:
    - compile_dbench|bool

- name: Run autogen for dbench
  command: "./autogen.sh"
  tags: [ 'dbench' ]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool

- name: Run configure for dbench
  command: "./configure"
  tags: [ 'dbench' ]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool

- name: Get nproc
  command: "{{ num_jobs }}"
  tags: [ 'git', 'dbench' ]
  register: nproc
  when:
    - compile_dbench|bool

- name: Build dbench
  tags: [ 'git', 'dbench' ]
  make:
    chdir: "{{ dbench_data }}"
    jobs: "{{ nproc.stdout }}"
  when:
    - compile_dbench|bool

- name: Install dbench
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{  make }} install"
  tags: [ 'git', 'dbench' ]
  args:
    chdir: "{{ dbench_data }}"
  when:
    - compile_dbench|bool
