---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Verify local build QEMU installation
  stat:
    path: "{{ qemu_bin_path }}"
  register: qemu_present
  changed_when: true
  failed_when: qemu_present.stat.exists and not qemu_present.stat.executable
  tags: [ 'qemu', 'verify' ]
  when:
    - qemu_build|bool

- name: Install build-deps for QEMU as per each Linux distribution
  include_tasks: install-deps/main.yml
  when:
    - qemu_build|bool
    - qemu_force_install_if_present|bool or not qemu_present.stat.exists

- name: Assume we won't build QEMU first
  set_fact:
    build_qemu_now: False
  tags: vars

- name: Annotate when we are building QEMU
  set_fact:
    build_qemu_now: True
  when:
    - qemu_build|bool
    - qemu_force_install_if_present|bool or (qemu_present.stat is not defined)
  tags: vars

- name: Ensure that {{ local_dev_path }} exists
  file:
    path: "{{ local_dev_path }}"
    state: directory
  tags: [ 'qemu', 'build-deps' ]
  when:
    - build_qemu_now|bool

- name: git clone QEMU
  environment:
    GIT_SSL_NO_VERIFY:  true
  git:
    repo: "{{ qemu_git }}"
    dest: "{{ qemu_data }}"
    version: "{{ qemu_version }}"
  when:
    - build_qemu_now|bool

- name: Nuke old build directory
  file:
    path: "{{ qemu_build_dir }}"
    state: absent
  tags: [ 'qemu', 'build-deps' ]
  when:
    - build_qemu_now|bool

- name: Run configure for QEMU
  command: "./configure --target-list={{ qemu_target }}"
  tags: [ 'qemu', 'configure' ]
  args:
    chdir: "{{ qemu_data }}"
  when:
    - build_qemu_now|bool

- name: Get nproc
  command: "{{ num_jobs }}"
  tags: [ 'qemu', 'configure' ]
  register: nproc
  when:
    - build_qemu_now|bool

- name: Build QEMU
  make:
    chdir: "{{ qemu_data }}"
    jobs: "{{ nproc.stdout }}"
  tags: [ 'qemu', 'build' ]
  when:
    - build_qemu_now|bool

- name: Install QEMU
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{ make }} install"
  args:
    chdir: "{{ qemu_data }}"
  tags: [ 'qemu', 'install' ]
  when:
    - build_qemu_now|bool
