- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true

- name: Insert udev rule to create siw device on the target host
  become: yes
  become_method: sudo
  ansible.builtin.template:
    src: "udev-rule.j2"
    dest: "/usr/lib/udev/rules.d/99-siw.rules"
    owner: "root"
    group: "root"
    mode: "0644"
    force: false

- name: Force the target host to reload its udev ruleset
  become: yes
  become_method: sudo
  ansible.builtin.command: "udevadm control --reload"
